---
title: Neil Hastings
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Blog of Neil Hastings
name: Neil's Life Journey
url: http://indytechcook.com
author: Neil Hastings
baseurl: http://indytechcook.com
exclude:
- Gemfile
- Gemfile.lock
- tasks
- todo.md
- jekyll.thor
markdown: rdiscount
pygments: false
lsi: true
paginate: 10
permalink: "/:title"
asset_pipeline:
  gzip: true
tag_dir: tag
