title: "Technology, Food and Random Thoughts"
descritpion: Blog of Neil Hastings
name: Neil Hastings

exclude: [Gemfile,Gemfile.lock,tasks,todo.md]

markdown: rdiscount
pygments: false
lsi: false
timezone: America/New_York
paginate: 10
permalink: /:title

asset_pipeline:
  gzip: true

tag_dir: tag
